package entities;
// Generated Jul 25, 2012 3:05:56 AM by Hibernate Tools 3.2.1.GA



/**
 * Treatment generated by hbm2java
 */
public class Treatment  implements java.io.Serializable {


     private Integer treatmentid;
     private String treatment;
     private double price;

    public Treatment() {
    }

    public Treatment(String treatment, double price) {
       this.treatment = treatment;
       this.price = price;
    }
   
    public Integer getTreatmentid() {
        return this.treatmentid;
    }
    
    public void setTreatmentid(Integer treatmentid) {
        this.treatmentid = treatmentid;
    }
    public String getTreatment() {
        return this.treatment;
    }
    
    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


